name = "codepen-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "codepen_pro_jwt_secret_2024_v1_x9k2m5"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "codepen-pro-db"
database_id = "9d47cc60-07ec-4cc5-9672-66168fd2f39d"

# KV Namespace for files
[[kv_namespaces]]
binding = "FILES"
id = "768eedf98a15496dab489045387a7995"
